generic_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include("store.urls")),
    path('',include("my_app.urls")),
    path('', include('django.contrib.auth.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path(r'products/', views.products, name='prods'),
    path(r'products/<str:name>/', views.spesproducts, name='spess'),
    path(r'remove/<str:name>/', views.remove, name='remove'),
    path(r'login/', views.login , name='login'),
    path(r'signin/', views.sign_in , name='signin'),
    path(r'cart/', views.cart, name='cart'),
    path(r'category/', views.category, name='category'),
    path(r'category/<str:name>/', views.spesscat, name='spesscat'),
    path(r'test/', views.test, name='test'),
    path(r'profile/', views.profile, name='profile'),
    path(r'checkout/', views.checkout, name='checkout'),
    path(r'wishlist/', views.wishlist, name='wishlist'),
    path(r'log/', views.user_login, name='userlogin'),
    path(r'products/<str:username>/<str:name>/purchase/', views.purchase_product, name='product_purchase'),
    ]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models

class DefaultImages(models.Model):

    def __str__(self):
        return self.name
    
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='default_images/')


class Category(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=100, null=True)
    quantity = models.IntegerField(null=True)



class Products(models.Model):
    def __str__(self):
        return self.name
    
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    order_amount = models.IntegerField(default=0)
    name = models.CharField(max_length=200)
    code = models.IntegerField(unique=True)
    sellp = models.FloatField()
    buyp = models.FloatField(default=0)
    quantity_in_stock = models.IntegerField(default=0,)
    cart = models.BooleanField(default=False)
    image = models.ImageField(upload_to='products/', null=True)



class Users(User):
    def __str__(self):
        return self.firstname
    
    products = models.ManyToManyField(Products, default='none',related_name='user_products')
    firstname = models.CharField(max_length=200)
    phone = models.IntegerField(unique=True)
    image = models.ImageField(upload_to='users/', null=True)

store/forms.py
from django import forms
from django.forms import ModelForm, TextInput, EmailInput,PasswordInput,NumberInput

from .models import Users, Products

class UsersForm(ModelForm):
    class Meta:
        model = Users
        fields = ['first_name', 'lastname', 'phone', 'id', 'email', 'password']
        
    first_name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class':'label',
        'style':'width: 200px;height: 20px;border-radius: 0.3vw 0.3vw 0.3vw 0.3vw;border-style: groove;border-width: .1vw;border-color: black;'
        }))
    lastname = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class':'label',
        'style':'width: 200px;height: 20px;border-radius: 0.3vw 0.3vw 0.3vw 0.3vw;border-style: groove;border-width: .1vw;border-color: black;'
        }))
    phone = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class':'label',
        'style':'width: 200px;height: 20px;border-radius: 0.3vw 0.3vw 0.3vw 0.3vw;border-style: groove;border-width: .1vw;border-color: black;'
        }))
    id = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class':'label',
        'style':'width: 200px;height: 20px;border-radius: 0.3vw 0.3vw 0.3vw 0.3vw;border-style: groove;border-width: .1vw;border-color: black;'
        }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class':'label',
        'style':'width: 200px;height: 20px;border-radius: 0.3vw 0.3vw 0.3vw 0.3vw;border-style: groove;border-width: .1vw;border-color: black;'
        }))
    password = forms.CharField(max_length=400,widget=forms.PasswordInput(attrs={
        'class':'label',
        'style':'width: 200px;height: 20px;border-radius: 0.3vw 0.3vw 0.3vw 0.3vw;border-style: groove;border-width: .1vw;border-color: black;'
        }))

class ProductsForm(ModelForm):
    class Meta:
        model = Products
        fields = ['amount', 'cart']
    
    amount = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class':'label',
        'style':'width: 240px;height: 35px; border-radius: 0.3vw 0vw 0vw 0.3vw; border-style: solid;border-width: .1vw;border-color: grey; margin-right: -5px; margin-top: -1px;',
        'placeholder':'AMOUNT'
        }), min_value=1, required=True)
        
    cart = forms.BooleanField(widget=forms.widgets.CheckboxInput(attrs={
        'class':'label'
        }), required=False, disabled=False, initial=True)
    

store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from .models import Products, Users, Category, DefaultImages
from .forms import UsersForm, ProductsForm
from django.views.generic import DetailView
from django.contrib import messages

default_thumbnail = DefaultImages.objects.get(name__startswith='default')

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request)
            # Redirect to a success page.
            return redirect('/store/products/')
        else:
            # Return an 'invalid login' error message.
            error_message = "Invalid username or password."
            return render(request, 'login.html', {'error_message': error_message})
    else:
        return render(request, 'log.html')

def wishlist(request):
    return render(request, 'wishlist.html')
    
def sign_in(request):
    if request.method=='POST':
        form = UsersForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            lastname = form.cleaned_data['lastname']
            phone = form.cleaned_data['phone']
            id = form.cleaned_data['id']
            email = form.cleaned_data['email']
            password  = form.cleaned_data['password']
            thisuser = Users(firstname=first_name, lastname=lastname, phone=phone, ids=id, email=email, password=password)
            thisuser.save()
            return render(request, 'tests.html')
    else:
        form = UsersForm()
    return render(request, 'tests.html', {'form':form})

def products(request):
    data = Products.objects.all()
    return render(request, 'products.html', {'data':data, 'default_thumbnail':default_thumbnail})

def cart(request):
    if request.user.is_authenticated:
        logged_in_user = request.user
    #user = get_object_or_404(Users, username=logged_in_user)
    user = Users.objects.get(username=logged_in_user)
    #product = Products.objects.all()
    user_products = user.products.all()

    context = Products.objects.all()
    users = Users.objects.all()
    total = total_to_checkout()
    return render(request, 'cart.html', {"context":context, "total":total, 'default_thumbnail':default_thumbnail, 'users':users, "logged_in_user":logged_in_user, 'user_products':user_products})


    
def spesscat(request,name):
    info = get_object_or_404(Category, name=name)
    prods = Products.objects.filter(category=info)
    return render(request, 'spesscat.html', {'info':info, 'prods':prods})

def remove(request,name):
    if request.user.is_authenticated:
        logged_in_user = request.user
    
    info = Products.objects.get(name=name)
    user = Users.objects.get(username=logged_in_user)
    user.products.remove(info)

    info.order_amount = 0
    info.cart = False
    info.save()
    return cart(request)

	
def spesproducts(request,name):
    # takes name from database to use as a product url
    if request.user.is_authenticated:
        logged_in_user = request.user

    info = Products.objects.get(name=name)
    active_user = Users.objects.get(username=logged_in_user)
    active_user.products.add(info)
    

    if request.method=='POST':
        form = ProductsForm(request.POST)
        if form.is_valid():
            amt = form.cleaned_data['amount']
            info.cart = True
            info.order_amount=amt
            info.save()
            return cart(request)
    else:
        form = ProductsForm()
    return render(request, 'product2.html', {'info':info, 'form': form, 'default_thumbnail':default_thumbnail, 'logged_in_user':logged_in_user})

def login(request):
    if request.method=='POST':
        form = UsersForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            password  = form.cleaned_data['password']
            return render(request, 'login.html', {
                "first_name":first_name,
                'password':password,
                })
    else:
        form = UsersForm()
    return render(request, 'login.html', {'form': form})


def category(request):
    data = Category.objects.all()
    return render(request, 'category.html', {'data':data})

def test(request):
	return render(request, 'modeltemp.html')
	
def profile(request):
    
	return render(request, 'profile.html')
	
def checkout(request):	
    item = Products.objects.all()
    return render(request, 'my_app:index.html')

def total_to_checkout():
    pass
    # multiplies amount by selling price
    # adds subtotals together for full price checkout
    data = Products.objects.values_list('order_amount', 'sellp')
    result = []
    for nested_tuple in data:
        multiply = nested_tuple[0]*nested_tuple[1]
        result.append(multiply)
    ans = sum(result)
    return int(ans)

def purchase_product(request, username, name):
    product = get_object_or_404(Products, name=name)
    user = get_object_or_404(Users, username=username)

    if product.order_amount > 0 and product.quantity > 0:
        # Perform the purchase logic here, for example, updating product quantity and user's purchased products
        product.order_amount -= 1
        product.quantity_in_stock -= 1
        product.save()

        # Add the purchased product to the user's products using the foreign key relationship
        user.products.add(product)
        user.save()

        messages.success(request, f'You have successfully purchased {product.name}.')
    else:
        messages.error(request, f'Sorry, {product.name} is out of stock.')

    # Redirect the user back to the product detail page after the purchase attempt
    return render(request, 'product_detail.html', {'product': product, 'user': user})

store/templates/base.html
{% extends 'products.html' %}
<!DOCTYPE html>
<html>
{% load static %}
<html style='backdrop-filter: blur(1px) saturate(7);' lang='en'>
<head>
  <meta charset="utf-8">
  <link rel='stylesheet' href="{% static 'store/signin.css' %}">
  <link rel='shortcut icon' href='../../media/regularshow.png' type='image/x-icon'>
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
{% block content %}
<body><div id="cen">
  <h1 id='signin'>LOGIN_IN</h1>
  <div id='parent'>
  <main>
  </main></div>
  <p style="display: flex; align-items: center; justify-content: center;">don't have an account ? signin <a href=''>here</a></p>
  <p style="display: flex; align-items: center; justify-content: center;"><a href="/store/products/">view our products</a></p></div>
  {% endblock %}
</body>
</html>

store/templates/cart.html
{% extends 'products.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cart</title>
</head>
<body>
    {% block content %}
    <p>user: {{logged_in_user}}</p>
    <h2>my orders</h2>
    <div class="container">
    <div class="row mt-1">
        {% for x in user_products %}
        {% if x.cart == True %}
        <div class="col-6 col-md-2 mb-4">
          <div class="card m-1">
            <img src="{{x.image.url}}" class="card-img-top" alt="Placeholder Image">
            <div class="card-body">
              <h5 class="card-title text-truncate overflow-hidden" style="max-width: 200px;">{{x}}</h5>
              <!--p class="card-text">ksh {{x.sellp}}</p-->
              <p class="card-text text-truncate overflow-hidden" style="max-width: 200px;">{{x.amount}} pcs Ksh : {{x.get_total}}</p>
              <a href="\store\remove\{{x.name}}\" style="text-decoration: none;"> remove <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
              </svg></a>
              <!--a href="#" class="btn btn-primary">Learn More</a-->
            </div>
          </div>
        </div>
  
    {% elif x.cart == False %}
    {% else %}
    <P>error on <b style="color: red;">{{x.name}}</b> amount cannot be negative > <b style="color: red;">{{x.amount}}</P>
    {% endif %}
    {% endfor %}
    </div>
    {% for x in users %}
    {% if x.is_authenticated %}
    {{x}}
    {% endif %}
    <ol>test
      {% for x in user_products %}
      <li>
        {{x}}
      </li>
      {% endfor %}
    </ol>
    {% endfor %}
    <div><a href="{% url 'store:prods' %}" style="color: black; text-decoration: none;"><button style="margin: 10px; border-radius: 2px; border-style: none; background-color: aquamarine;"><< continue shopping</button></a></div>
    <div class="container">total : ksh {{total}}</div>
        <form action="/pay/" method="post">
        {% csrf_token %}
        <input style="margin: 10px; border-radius: 2px; border-style: none; background-color: aquamarine;" type="submit" value="checkout"> {{x.chckt}}
        </form>
    </div>
    {% endblock %}
</body>
</html>

store/templates/category.html
{% extends 'products.html' %}
{% load static %}

<body>
    {% block content %}
    <h2>categories</h2>
    {% if data|length == 0 %}
    <div><p>you have not specified categories yet !</p></div>
    {% else %}
    <div>
        {% for data in data %}
        <ul>
            <li>
                <a href="/store/category/{{data}}/" style="color: black; text-decoration: none;">{{data}} <br></a>
            </li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    {% endblock %}
</body>

store/templates/checkout.html
{% extends 'products.html' %}
{% block content %}

{% for individual in item %}
{% if individual.cart == True %}
<div class="border border-dark p-3" style="background: white;">
    <img src="/static/browse/products/{{individual.name}}.jpeg" alt="">
    <div>{{individual}}</div>
    <br>
    <div>ksh {{individual.sellp}}</div>
    <br>
    <div>amount: (<span style="color: aqua;">{{individual.amount}}</span>) total = <span style="color: green;"></span></div>
</div>
{% endif %}
{% endfor %}

{% endblock %}

store/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

store/templates/img.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% for x in img %}
<div>{{x}}</div>
<hr>
<div>
    <img src="{{x.image.url}}" alt="{{x.image.url}}">
</div>
<hr>
<div><a href="{{x.image.url}}">{{x}}</a></div>
{% endfor %}
</body>
</html>

store/templates/log.html
{% extends 'products.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
{% block content %}
<body>
    <h2>Login</h2>
    <form method="post" action="{% url 'store:userlogin' %}">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required><br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br>
        <button type="submit">Login</button>
    </form>
    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}
    {% endblock %}
</body>
</html>

store/templates/login.html
{% extends 'products.html' %}
<!DOCTYPE html>
{% load static %}
<html style='backdrop-filter: blur(1px) saturate(7);' lang='en'>
<head>
    <link rel='stylesheet' href="{% static 'css\bootstrap.css' %}">
    <link rel='shortcut icon' href='../../media/regularshow.png' type='image/x-icon'>
    <meta charset='UTF-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>steve arts | LOG IN</title>
</head>
<body>
    {% block content %}
	<div class="container">
    <h1 id='signin'>LOGIN IN</h1>
    <div class='container'>
        <form action="\store\products\" method="post">
            {% csrf_token %}
            <div style="display: block;">
                {{form.first_name.label_tag}}
                {{form.first_name}}
            </div>
            <br>
            <div>
                {{form.password.label_tag}}
                {{form.password}}
            </div>
            <br>
            <div>
            <input type="submit" value="login">
            </div>
        </form> 
    </div>
    <p style="display: flex; align-items: center; justify-content: center;">don't have an account ? signin <a href=''>here</a></p>
    <p style="display: flex; align-items: center; justify-content: center;"><a href="{% url 'store:prods' %}">view our products</a></p></div>
    {% endblock %}
</body>
<script>
</script>
</html> 

store/templates/name.html
<form action="/browse/name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit">
</form>

store/templates/product2.html
{% extends 'products.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" style="font-family: sans-serif;">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'browse\product2.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>products</title>
</head>
{% block content %}
<body>
	<p>user: {{logged_in_user}}</p>
	<div class="row">
		<div class="col-6 col-md-2 mb-4 mt-4">
		  <div class="card m-1 text-truncate overflow-hidden">
			<img src="{{default_thumbnail.image.url}}" class="card-img-top" alt="Placeholder Image">
			<div class="card-body">
			  <h5 class="card-title">{{info.name}}</h5>
			  <p class="card-text">ksh {{info.sellp}}</p>
			  <!--a href="#" class="btn btn-primary">Learn More</a-->
			</div>
		  </div>
		</div>
	  </div>
	  <div class="m-1">
	    <form action="" method="post">
		{% csrf_token %}
		{{form.amount}}
		{{form.amount.errors}}
		{{form.cart.errors}}    
		<input type="submit" value="order" style="margin-left: 0px; height: 35px; border-radius: 0vw 0.3vw 0.3vw 0vw; border-style: groove;border-width: .1vw;border-color: grey;">
		</form>
		{{amount}}
        {% endblock %}
	</div>
	</div>

</body>
</html>

store/templates/product_detail.html
{% extends "products.html" %}
<!DOCTYPE html>
<html>
<head>
    <title>Product Detail</title>
</head>
<body>
    {% block content %}
    <h1>Product Detail</h1>
    <h2>{{ product.name }}</h2>
    <p>Category: {{ product.category }}</p>
    <p>Code: {{ product.code }}</p>
    <p>Amount: {{ product.amount }}</p>
    <p>Quantity in Stock: {{ product.quantity }}</p>
    <p>Selling Price: ${{ product.sellp }}</p>
    
    <h2>User Information</h2>
    <p>Name: {{ user.firstname }}</p>
    <p>Phone: {{ user.phone }}</p>
    
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% endblock %}
</body>
</html>

store/templates/profile.html
{% extends 'products.html' %}
{% load static %}
<html>
<head>
    <link rel='stylesheet' href="{% static 'browse\css\bootstrap.css' %}">
    <link rel='shortcut icon' href='../../media/regularshowcpy2.png' type='image/x-icon'>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	{% block content %}
	<h2>Profile</h2>
	<div class="card m-1" style="width: 200px;">
		<img src="https://via.placeholder.com/150" class="card-img-top" alt="Placeholder Image">
		<div class="card-body">
		  <h5 class="card-title">{{user}}</h5>
		  <p class="card-text"></p>
		  <!--a href="#" class="btn btn-primary">Learn More</a-->
		</div>
  <div class="mb-3">
  {% csrf_token %}
  <input class="form-control" type="file" id="formFile">
	</div>
  	</div>
	{% endblock %}
</body>
</html>

store/templates/signin.html
<!DOCTYPE html>
{% load static %}
<html style='backdrop-filter: blur(1px) saturate(7);' lang='en'>
<head>
    <link rel='stylesheet' href="{% static 'browse\signin.css' %}">
    <link rel='shortcut icon' href='../../media/regularshow.png' type='image/x-icon'>
    <meta charset='UTF-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>steve arts | SIGN IN</title>
</head>
<body>
    <h1 id='signin'>SIGN IN</h1>
    <div id='parent'>
        <form action="\browse\test\" method="post">
        {% csrf_token %}
            <input type="button" value="signin" onclick="mk()">
        </form> 
    </div>
    <p style="display: flex; align-items: center; justify-content: center;">have an account ? login <a href='{% url "browse:login" %}'>here</a></p>
    <p style="display: flex; align-items: center; justify-content: center;"><a href="{% url 'browse:prod' %}">view our products</a></p>
</body>
<script src="{% static 'browse\display.js' %}">
</script>
</html> 

store/templates/spesscat.html
{% extends 'products.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{info}}</title>
</head>
<body>
    {% block content %}
    <div class="container">
        <h3>{{info}}</h3>
        <div class="row mt-1">
            {% for item in prods %}
            <div class="col-6 col-md-2 mb-4">
              <a href="/store/products/{{item}}" style="text-decoration: none;">
              <div class="card m-1 text-truncate overflow-hidden" style="max-width: 200px;">
      
                <img src="{{item.image.url}}" class="card-img-top" alt="Placeholder Image">
      
                <div class="card-body">
                  <h5 class="card-title">{{item}}</h5>
                  <p class="card-text">ksh {{item.sellp}}</p>
                  <!--a href="#" class="btn btn-primary">Learn More</a-->
                </div>
              </div>
            </a>
            </div>
      
            <!-- Repeat similar blocks for the remaining cards -->
            {% endfor %}
          </div>
    </div>
    {% endblock %}
</body>
</html>